
# tap repositories and their packages

tap homebrew/core
brew autoconf
brew automake
brew bash
brew bash-completion
brew berkeley-db
brew bison
brew bison@2.7
brew cabal-install
brew cairo
brew circleci
brew ctop
brew docker-machine
brew flac
brew fontconfig
brew freetype
brew fribidi
brew gcc
brew gd
brew gdbm
brew gettext
brew ghc
brew glances
brew glib
brew gmp
brew go
brew graphite2
brew graphviz
brew gts
brew harfbuzz
brew highlight
brew htop
brew icu4c
brew isl
brew jack
brew jasper
brew jpeg
brew jq
brew libev
brew libevent
brew libffi
brew libiconv
brew liblo
brew libmpc
brew libogg
brew libpng
brew libressl
brew libsamplerate
brew libsndfile
brew libtermkey
brew libtiff
brew libtool
brew libuv
brew libvorbis
brew libvterm
brew libxml2
brew libyaml
brew libzip
brew lua
brew luajit
brew lzo
brew mas
brew mcrypt
brew mhash
brew mpfr
brew msgpack
brew ncurses
brew netpbm
brew oniguruma
brew openssl@1.1
brew pango
brew pcre
brew perl
brew pixman
brew pkg-config
brew python
brew python@3.8
brew re2c
brew readline
brew reattach-to-user-namespace
brew ruby
brew ruby-build
brew sphinx-doc
brew sqlite
brew tmux
brew tree
brew unibilium
brew utf8proc
brew vim
brew webp
brew weighttp
brew xz
brew zlib

tap homebrew/bundle

tap homebrew/cask-versions
cask sequel-pro-nightly

tap homebrew/cask

tap argon/mas

tap heroku/brew
brew heroku
brew heroku-node

tap kadaan/php

tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew python@2

# App Store applications
appstore 1451177988 Carbonize (2020.1)
appstore 947393436 Drive (1.16)
appstore 682658836 GarageBand (10.3.4)
appstore 408981434 iMovie (10.1.14)
appstore 1025822138 iStatistica (4.6.1)
appstore 409183694 Keynote (10.0)
appstore 539883307 LINE (5.24.1)
appstore 409203825 Numbers (10.0)
appstore 409201541 Pages (10.0)
appstore 1176895641 Spark (2.6.2)
appstore 497799835 Xcode (11.4.1)
